import numpy as np
import matplotlib.pyplot as plt
import csv
import logging
from datetime import date
import os
import queue
import sys

# create logger
logger = logging.getLogger('psim_logger')
logger.setLevel(logging.DEBUG)  # Log everything (DEBUG level or higher)

# one handler for all loggers
if not logger.handlers:
    # create a file handler to log to a file
    file_handler = logging.FileHandler(f'{date.today()}_psim_log_file.log')
    file_handler.setLevel(logging.DEBUG)

    # create a stream handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.DEBUG)

    # define log format
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(formatter)
    console_handler.setFormatter(formatter)

    # add file handler to logger
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)
    

def disk_logging_worker(log_queue, filename, header):
    """
    Thread worker that waits for data chunks and appends them to disk.
    
    Args:
        log_queue: Queue receiving (t_chunk, data_chunk) tuples.
        filename: Target CSV file.
        header: List of column names.
    """
    #print(f"Starting Disk Logger for {filename}...", end="")
    logger.info(f"[disk_logging_worker] Starting Disk Logger for {filename}...")
    
    # Check if file exists and start fresh if it does
    if os.path.exists(filename):
        os.remove(filename)
    
   
    # Let's use a flag to track if we need to write the header
    need_header = True

    while True:
        try:
            # Block until a chunk is available
            item = log_queue.get()
            
            # Check for shutdown signal
            if item is None:
                #print("Disk Logger finishing...")
                logger.info('[disk_logging_worker] Disk Logger finished.')
                break
            
            t_chunk, data_chunk = item
            
            # Write to disk
            # We open and close the file every chunk to ensure OS flushes buffers
            # This is safer against crashes than keeping it open.
            with open(filename, 'a', newline='') as f:
                writer = csv.writer(f)
                
                # Write Header only once
                if need_header:
                    full_header = ['PSim_Time'] + header
                    writer.writerow(full_header)
                    need_header = False
                
                # Write Data
                for idx in range(len(t_chunk)):
                    row_list = data_chunk[idx].tolist()
                    row_list.insert(0, float(t_chunk[idx]))
                    writer.writerow(row_list)
                    
            # Mark task as done
            log_queue.task_done()
            
        except Exception as e:
            #print(f"[DISK ERROR] Could not write to log: {e}")
            logger.error(f'[disk_logging_worker] Could not write to log: {e}')

    #print("Disk Logger stopped.")
    logger.info(f'[disk_logging_worker] Disk Logger stopped.')



def load_from_disk(filename):
    """
    Helper to read the full CSV back into memory for plotting at the end.
    Returns: t_vector, data_matrix
    """
    try:
        # Load using numpy (skip header)
        raw = np.loadtxt(filename, delimiter=',', skiprows=1)
        
        # Split Time (col 0) and Data (cols 1+)
        t_vec = raw[:, 0]
        data = raw[:, 1:]
        return t_vec, data
    except Exception as e:
        #print(f"Could not load log file for plotting: {e}")
        logger.error(f'[load_from_disk] Could not load log file for plotting: {e}')
        return np.array([]), np.array([])

# Keep make_plots as is
# auxiliary function for plotting results
def make_plots(x_data=np.array([0,1,2]), y_data=np.array([0,1,2]), \
                header=['PSim_Time', 'u', 'v', 'w', 'p', 'q', 'r', 'phi', 'theta', 'psi', 'lat', 'lon', 'h', 'V_N', 'V_E', 'V_D', 'dA', 'dE', 'dR', 'dT1', 'dT2', 'dgsp', 'brake'], skip=0)->plt.plot:

    '''
    Function to plot results.
    Inputs: 
        x_data - time vector
        y_data - n-dimentional array with parameters to be plotted
        header has standard sequence of parameters/labels as generated by simulator
        skip: number of header items to skip
    '''
    if x_data.size == 0: return None
    plotlist = []

    counter = 1
    myfig = plt.figure(figsize = (16,(y_data.shape[1]*4)))
    myfig.patch.set_edgecolor('w')
    plt.subplots_adjust(hspace = 0.0)
    for y_data_idx in range(y_data.shape[1]):
        strip_chart_y_data = y_data[:,y_data_idx]
        ax = myfig.add_subplot(y_data.shape[1], 1, counter)
        ax.plot(x_data, strip_chart_y_data)
        plt.ylabel(header[y_data_idx + skip])
        plt.grid(True)
        counter += 1
    return myfig


def save2disk(filename:str, x_data=np.array([0,1,2]), y_data=np.array([0,1,2]), \
                header=['u', 'v', 'w'], skip=0)->None:
    '''
    saves data to disk
    '''
    with open(filename, 'w') as f:
        y_dim = y_data.shape[1]
        data_header = header[skip:y_dim]
        data_header.insert(0, 'PSim_Time')
        writer = csv.writer(f)
        writer.writerow(data_header)
        for idx, row in enumerate(y_data):
            row_list = row.tolist()
            row_list.insert(0, x_data[idx].astype('float'))
            writer.writerow(row_list)





# OFFLINE control inputs creation
def get_doublet(t_vector:np.ndarray, t:float=0, duration:float=1, amplitude:float=0.1)->np.ndarray:
    '''
    calculates a doublet input
    inputs:
        t_vector: time vector
        t: value at which the doublet should start
        duration: duration of the high/low input states
        amplitude: multiplication factor to set amplitude
    returns:
        doublet vector
    '''
    rise_idx = np.argmax(t_vector>=t)
    drop_idx = np.argmax(t_vector >=(t+duration/2))
    zero_idx = np.argmax(t_vector >=(t+duration))
    res = np.zeros(t_vector.shape)
    res[rise_idx:drop_idx] = 1 * amplitude
    res[drop_idx:zero_idx] = -1 * amplitude
    return res


def get_step(t_vector:np.ndarray, t:float=0, amplitude:float=0.1)->np.ndarray:
    '''
    calculates a step input
    inputs:
        t_vector: time vector
        t: value at which the doublet should start
        amplitude: multiplication factor to set amplitude
    returns:
        step vector
    '''
    rise_idx = np.argmax(t_vector>=t)
    res = np.zeros(t_vector.shape)
    res[rise_idx:] = 1 * amplitude
    return res


def create_cmd(t_vector=np.zeros(5), input_channel:str='ail', cmd_type:str='doublet', at_time:float=0.0, duration:float=1.0, amplitude:float=0.0)->np.ndarray:
    '''
    helper function to create a doublet or step in a channel
    inputs:
        t_vector: time vector
        input_channel: selector for axis (see if/else below)
        cmd_type: selector for doublet or step
        at_time: value at which the inpute should start
        duration: duration of the high/low input states
        amplitude: multiplication factor to set amplitude
    returns:
        input_ch_number: integer with the index of command to be added to integration loop
        cmd: vector with command
    '''
    
    if input_channel == 'ail':
        input_ch_num = 0
    elif input_channel == 'elev':
        input_ch_num = 1
    elif input_channel == 'rud':
        input_ch_num = 2
    elif input_channel == 'thru':
        input_ch_num = 3
    elif input_channel == 'none' or input_channel == 'None':
        cmd = np.zeros(t_vector.shape)
        input_ch_num = 0
    else:
        input_ch_num = -1
    
    
    if cmd_type=='doublet' and input_ch_num>=0:
        cmd = get_doublet(t_vector, t=at_time, duration=duration, amplitude=amplitude)
    elif cmd_type=='step' and input_ch_num>=0:
        cmd = get_step(t_vector, t=at_time, amplitude=amplitude)
    else:
        print('error - command type not recognized')
        cmd = np.zeros(t_vector.shape)
        input_ch_num = 0
        
    return input_ch_num, cmd